version: "3.9"
services:
  stepbot:
    build: .
    container_name: stepbot
    restart: always  
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro	
      - .:/app
    environment:
      - NODE_ENV=production

